services:
  my-app:
    image: shashkist/fullstack-project-tacos:2.0
    ports:
      - 8081:8080
    environment:
      - SPRING_PROFILES_ACTIVE=ilia
    #  - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tacosProject?createDatabaseIfNotExist=true
  db:
    image: mysql:8.4.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - sql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 5012:80

volumes:
  sql-data:
